// Generates src/sidc-literal-tables.ts: the 2525C value sets as string-literal types, used by
// the compile-time SIDC literal check (src/sidc-literal.ts). Run after the tables change:
//   npx tsx scripts/build-literal-types.ts
// tests/sidc-literal.test.ts fails when the generated file is out of date.
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { catalog } from "../src/data/index";
import {
  DIMENSIONS,
  ORDERS_OF_BATTLE,
  STANDARD_IDENTITIES,
  STATUSES,
  SYMBOL_MODIFIERS,
} from "../src/legacy/fields";

const union = (xs: Iterable<string>) => {
  const u = [...new Set(xs)].sort();
  return u.length ? u.map((x) => JSON.stringify(x)).join(" | ") : "never";
};
const SCHEMES = ["S", "G", "I", "O", "E"] as const;

export function generate(): string {
  const fnIds = new Map<string, Set<string>>();
  const metoc = new Set<string>();
  for (const { template: t } of catalog) {
    if (t[0] === "W") {
      metoc.add(t);
      continue;
    }
    const k = t[0]! + t[2]!;
    if (t[2] === "-") continue; // hierarchy headings are not symbols
    (fnIds.get(k) ?? fnIds.set(k, new Set()).get(k)!).add(t.slice(4, 10));
  }
  const out: string[] = [
    "// Generated by scripts/build-literal-types.ts from the MIL-STD-2525C tables. Do not edit.",
    "",
    `export type AffiliationChar = ${union(Object.keys(STANDARD_IDENTITIES))};`,
    "",
    "export interface SchemeTables {",
  ];
  for (const s of SCHEMES) {
    out.push(`  ${s}: {`);
    out.push(`    dimension: ${union(Object.keys(DIMENSIONS[s]))};`);
    out.push(`    status: ${union(Object.keys(STATUSES[s]))};`);
    out.push(`    modifier: ${union(Object.keys(SYMBOL_MODIFIERS[s]))};`);
    out.push(`    orderOfBattle: ${union(Object.keys(ORDERS_OF_BATTLE[s]))};`);
    out.push("  };");
  }
  out.push(
    "}",
    "",
    "/** Function IDs (positions 5-10) per scheme + dimension. */",
  );
  out.push("export interface FunctionIds {");
  for (const [k, ids] of [...fnIds].sort(([a], [b]) => a.localeCompare(b)))
    out.push(`  ${k}: ${union(ids)};`);
  out.push("}", "", "/** Complete METOC SIDCs (no user-defined positions). */");
  out.push(`export type MetocSidc = ${union(metoc)};`, "");
  return out.join("\n");
}

const target = new URL("../src/sidc-literal-tables.ts", import.meta.url);
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(target, generate());
  console.log("wrote", fileURLToPath(target));
}
